// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmxZUS4orrV9o0NPlJmGNSDTzh5uvM5M',
    appId: '1:274262039847:web:c4fe47bc4aa1ab0c0a5d02',
    messagingSenderId: '274262039847',
    projectId: 'sahilecom',
    authDomain: 'sahilecom.firebaseapp.com',
    storageBucket: 'sahilecom.appspot.com',
    measurementId: 'G-S269256R26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0QkR6vgnw8nJh0ZRXL88mZQQey9P1lM',
    appId: '1:274262039847:android:1a80074bc4ed686e0a5d02',
    messagingSenderId: '274262039847',
    projectId: 'sahilecom',
    storageBucket: 'sahilecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB957apoV8QBkcjM4TC0fECjXxhu4nl6JE',
    appId: '1:274262039847:ios:d7a5e1ed38c61b5a0a5d02',
    messagingSenderId: '274262039847',
    projectId: 'sahilecom',
    storageBucket: 'sahilecom.appspot.com',
    iosClientId: '274262039847-kad3tnplqbq9iqs47sli8uk8c7iftlhd.apps.googleusercontent.com',
    iosBundleId: 'com.sahil.sahilweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB957apoV8QBkcjM4TC0fECjXxhu4nl6JE',
    appId: '1:274262039847:ios:566e9e0825cfe4250a5d02',
    messagingSenderId: '274262039847',
    projectId: 'sahilecom',
    storageBucket: 'sahilecom.appspot.com',
    iosClientId: '274262039847-4bk9nd6h92klm00n505k3g5gvd3mvs9r.apps.googleusercontent.com',
    iosBundleId: 'com.sahil.sahilweb.RunnerTests',
  );
}
